"""Add payment_id to properties table

Revision ID: b96c4a6ef5b9
Revises: 
Create Date: 2025-11-11 23:35:35.418459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b96c4a6ef5b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('payment_id', sa.UUID(), nullable=True))

    # --- NEW: Update existing NULL house_type values to a default before making it NOT NULL ---
    op.execute("UPDATE properties SET house_type = 'private home' WHERE house_type IS NULL")
    # --- END NEW ---

    op.alter_column('properties', 'house_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('properties', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('properties', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_unique_constraint(None, 'properties', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='unique')
    op.alter_column('properties', 'photos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('properties', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('properties', 'house_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('properties', 'payment_id')
    # ### end Alembic commands ###
