"""Add payment_status and approval_timestamp to properties table (with default)

Revision ID: e08b90822536
Revises: bf09ed8156fc
Create Date: 2025-11-14 22:41:27.776291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e08b90822536'
down_revision: Union[str, Sequence[str], None] = 'bf09ed8156fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add payment_status column as nullable=True first
    op.add_column('properties', sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=True))

    # Update existing rows to set a default value for payment_status
    op.execute("UPDATE properties SET payment_status = 'PENDING' WHERE payment_status IS NULL")

    # Alter payment_status column to nullable=False
    op.alter_column('properties', 'payment_status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'),
               nullable=False,
               existing_nullable=True)

    op.add_column('properties', sa.Column('approval_timestamp', sa.DateTime(), nullable=True))
    op.drop_index(op.f('properties_search_idx'), table_name='properties', postgresql_using='gin')
    op.drop_column('properties', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index(op.f('properties_search_idx'), 'properties', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('properties', 'approval_timestamp')
    op.drop_column('properties', 'payment_status')
    # ### end Alembic commands ###
