INSERT INTO properties (user_id, title, description, location, price, amenities, photos, status) VALUES
    (uuid_generate_v4(), 'Modern Apartment in Bole', 'A stunning, fully-furnished 2-bedroom apartment.', 'Bole, Addis Ababa', 25000.00, '["WiFi", "Generator", "Parking"]'::jsonb, '["p1_1.jpg", "p1_2.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Cozy Studio near Edna Mall', 'Perfect for a single professional.', 'Bole, Addis Ababa', 12000.00, '["WiFi", "Security"]'::jsonb, '["p2_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Family Home in CMC', 'Spacious 4-bedroom house with a large garden.', 'CMC, Addis Ababa', 45000.00, '["Garden", "Parking", "24/7 Water"]'::jsonb, '["p3_1.jpg"]'::jsonb, 'PENDING'),
    (uuid_generate_v4(), 'Luxury Villa with Pool', 'Exclusive villa in a gated community.', 'Old Airport, Addis Ababa', 80000.00, '["Swimming Pool", "Gym", "Sauna"]'::jsonb, '["p4_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Affordable Room in Piassa', 'A single room in a shared apartment.', 'Piassa, Addis Ababa', 5000.00, '[]'::jsonb, '[]'::jsonb, 'REJECTED'),
    (uuid_generate_v4(), 'Commercial Space for Rent', 'Ground floor commercial space ideal for a cafe.', 'Kazanchis, Addis Ababa', 35000.00, '["Main Road Access"]'::jsonb, '["p5_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'G+2 House in Ayat', 'A beautiful family home with 5 bedrooms.', 'Ayat, Addis Ababa', 38000.00, '["Parking", "Balcony"]'::jsonb, '["p6_1.jpg"]'::jsonb, 'PENDING'),
    (uuid_generate_v4(), 'Apartment with a View', '2-bedroom apartment on the 10th floor with a city view.', 'Hayahulet, Addis Ababa', 22000.00, '["Elevator", "Security"]'::jsonb, '["p7_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Small Office Space', 'An affordable office space for a startup.', '4 Kilo, Addis Ababa', 8000.00, '["WiFi"]'::jsonb, '[]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Traditional Ethiopian House', 'Experience authentic living in this beautiful traditional house.', 'Shiro Meda, Addis Ababa', 18000.00, '["Garden"]'::jsonb, '["p8_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Furnished Studio in Hawassa', 'A clean and modern studio in Hawassa.', 'Hawassa', 10000.00, '["WiFi", "Kitchenette"]'::jsonb, '["p9_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'L-Shaped House in Adama', 'A spacious house perfect for a large family.', 'Adama', 20000.00, '["Parking", "Garden"]'::jsonb, '["p10_1.jpg"]'::jsonb, 'PENDING'),
    (uuid_generate_v4(), 'Apartment in Bahir Dar', 'Enjoy the views of Lake Tana from this apartment.', 'Bahir Dar', 15000.00, '["Balcony"]'::jsonb, '["p11_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Guesthouse Rooms in Lalibela', 'Single rooms available for rent in a guesthouse.', 'Lalibela', 7000.00, '[]'::jsonb, '[]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Warehouse for Rent', 'Large warehouse space in an industrial area.', 'Dukem', 50000.00, '["Loading Dock"]'::jsonb, '[]'::jsonb, 'PENDING'),
    (uuid_generate_v4(), 'Condominium Unit', '2-bedroom condominium unit in a popular site.', 'Jemo, Addis Ababa', 9000.00, '[]'::jsonb, '["p12_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Shared Apartment for Students', 'Close to Addis Ababa University.', '6 Kilo, Addis Ababa', 4000.00, '["Shared Kitchen"]'::jsonb, '[]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Retail Shop in Merkato', 'A small shop in a high-traffic area.', 'Merkato, Addis Ababa', 18000.00, '[]'::jsonb, '[]'::jsonb, 'REJECTED'),
    (uuid_generate_v4(), 'Luxury Penthouse', 'Top-floor penthouse with panoramic city views.', 'Kazanchis, Addis Ababa', 120000.00, '["Rooftop Terrace", "Jacuzzi"]'::jsonb, '["p13_1.jpg"]'::jsonb, 'APPROVED'),
    (uuid_generate_v4(), 'Basic Room for Rent', 'A simple, unfurnished room.', 'Gofa, Addis Ababa', 3500.00, '[]'::jsonb, '[]'::jsonb, 'PENDING');
